name: Link check
on: [pull_request]
jobs:
  check-links:
    name: Run linkspector
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
